# Generated by Django 5.1.6 on 2025-06-14 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('dispensed', 'Dispensed'), ('partial', 'Partial'), ('unavailable', 'Unavailable')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescriptionheader')),
            ],
        ),
    ]
