# Generated by Django 5.1.6 on 2025-06-14 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('type', models.CharField(choices=[('lab', 'Lab'), ('scan', 'Scan'), ('note', 'Note'), ('referral', 'Referral'), ('prescription', 'Prescription')], max_length=20)),
                ('summary', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
