# Generated by Django 5.2.3 on 2025-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
